M48
; DRILL file {KiCad 7.0.5-7.0.5~ubuntu20.04.1} date Fri 23 Jun 2023 07:32:12 AM CEST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-06-23T07:32:12+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5-7.0.5~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X0.1083Y2.3071
X0.5843Y0.1457
X1.0728Y2.3071
T0
M30
